### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by akerouanton** [KnpLabs/rad-view-renderer#8]
Currently `symfony/framework-bundle` is required whereas only those symfony components are used :
- `symfony/http-kernel`
- `symfony/http-foundation`
- `symfony/dependency-injection`
- `symfony/config`

The `EngineInterface` coming from the `FrameworkBundle` should be replaced with the interface coming from `symfony/templating`.

**Comment by einenlum** [comment]
:+1:

**Comment by PedroTroller** [comment]
@NiR- not only : https://github.com/KnpLabs/rad-view-renderer/blob/master/src/Knp/Rad/ViewRenderer/Controller/Guesser.php#L5

**Comment by einenlum** [comment]
Ok so FrameworkBundle is a real dependency for now. Closing this issue, but feel free to reopen it if needed :) @NiR-
